version: "3"
services:
  react-app:
    image: social-app-react
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: social-app-server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
